export const ADD_MANUALS = 'ADD_MANUALS';
export const ADD_MANUAL = 'ADD_MANUAL';
export const MANUALS_LOADING = 'MANUALS_LOADING';
export const MANUALS_FAILED = 'MANUALS_FAILED';

export const ADD_CONCEPTS = 'ADD_CONCEPTS';
export const ADD_CONCEPT = 'ADD_CONCEPT';
export const CONCEPTS_LOADING = 'CONCEPTS_LOADING';
export const CONCEPTS_FAILED = 'CONCEPTS_FAILED';

export const ADD_AUTHORS = 'ADD_AUTHORS';
export const AUTHORS_LOADING = 'AUTHORS_LOADING';
export const AUTHORS_FAILED = 'AUTHORS_FAILED';

export const ADD_CLIENTS = 'ADD_CLIENTS';
export const CLIENTS_LOADING = 'CLIENTS_LOADING';
export const CLIENTS_FAILED = 'CLIENTS_FAILED';

export const ADD_EDUCATION = 'ADD_EDUCATION';
export const EDUCATION_LOADING = 'EDUCATION_LOADING';
export const EDUCATION_FAILED = 'EDUCATION_FAILED';

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const EXPERIENCE_LOADING = 'EXPERIENCE_LOADING';
export const EXPERIENCE_FAILED = 'EXPERIENCE_FAILED';

export const ADD_ABOUT = 'ADD_ABOUT';
export const ABOUT_LOADING = 'ABOUT_LOADING';
export const ABOUT_FAILED = 'ABOUT_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';